### ISSUE TITLE
Create an example

### ISSUE THREAD

**Issue by j0lv3r4** [j0lv3r4/next-csrf#1]

**Comment by ChuckJonas** [comment]
Any idea when you might be able to get around to this?  The current documentation seems to be pretty lacking.  An E2E example would clear things up.  

I have a couple specific questions are not fully answered in the documentation.

> When you initialize nextCsrf it will return the middleware
Where/how do you connect the `csrf` middlewear?  I assume this in a "Custom Server", but example code would be nice.

>Keep in mind that the token is valid only on the first request, since we create a new one on each request.

How are subsequent requests obtained?

**Comment by ChuckJonas** [comment]
nvm, i see it's a HOC.

**Comment by j0lv3r4** [comment]
hey @ChuckJonas 

There's an example coming on this PR https://github.com/j0lv3r4/next-csrf/pull/6

**Comment by j0lv3r4** [comment]
https://github.com/j0lv3r4/next-csrf/releases/tag/v0.2.1
