### ISSUE TITLE
"TypeError: Secret string must be provided."

### ISSUE THREAD

**Issue by Brawl345** [j0lv3r4/next-csrf#23]
I get this error when trying to use next-csrf while using the documentation 1:1. It thinks the CSRF_SECRET is empty, even though it is set in `.env`. 

It works when I prepend "NEXT_PUBLIC_" to the env variable but this would expose the secret to the browser: https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser (and I can also see this in the source code)

This is my csrf.js:

```js
// file: lib/csrf.js
import { nextCsrf } from "next-csrf";

const options = {
    secret: process.env.CSRF_SECRET
}

export const { csrf, csrfToken } = nextCsrf(options);
```

**Comment by j0lv3r4** [comment]
@Brawl345 I think you need to use `.env.local` instead of `.env`, I might be wrong, tho. Try Next.js' documentation [Loading Environment Variables](https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables).

**Comment by Brawl345** [comment]
Tried with .env.local and got the same error.

**Comment by onosendi** [comment]
Getting the same error. `console.log(process.env.CSRF_SECRET)` logs the correct secret, but still getting the error.

**Comment by haipham23** [comment]
Getting the same error. However, if I use a string instead of env (`{ secret: 'my_string' }`), it works.

**Comment by Get-DevVed-YT** [comment]
I got a similar error.

**Comment by brianhatchet** [comment]
You need to expose the environment variable to the browser side of the equation and then export the generated token down the component chain. The secret will then be built and minified/uglified and available to the the app.jsx page props.

NEXT_PUBLIC_CSRF_SECRET

**Comment by onosendi** [comment]
@brianhatchet That will absolutely leak the secret. View your page's source, you'll see the secret right in the document.

**Comment by brianhatchet** [comment]
I am not arguing with you, but I cannot find it in either the source or by grepping the bundles with Next 11.1.2

Now to play find the leak.

**Comment by brianhatchet** [comment]
I guess the only real way to do it safely would in getServerSideProps, but I am cannot get the generated token to match the httpOnlyCookie for the middleware. Hmmm.

**Comment by j0lv3r4** [comment]
@brianhatchet that's correct. The secret should stay in the server and never leak to the frontend. The only way to get the token is through `getServerSideProps` or an API route.

I'm taking time today to check the documentation and review issues. I will update y'all with more info later.

**Comment by brianhatchet** [comment]
Yeah, no, had to load it in chrome to parse everything. Nextjs just hard codes that secret in the bundle.  Thanks @j0lv3r4

**Comment by j0lv3r4** [comment]
Okay, there are two things:

* The documentation explains the implementation wrong. The `csrfToken` shouldn't be set up in a custom `_app.js` because it runs on both the client and server AND generates the token only on the server.
* The `csrfToken` should be set up on an SSR login page.

I'm preparing a pull request to clarify the points above and set up an `example/` folder with the right implementation.

**Comment by amit-viacon** [comment]
> Also, I found a way use the existing documentation to load the getServerSide props without any api calls. The answer is ES2020's dynamic imports.
> 
> ```
> export async function getServerSideProps() {
>     const { csrfToken } = await import("../lib/csrf");
>     return {
>         props: { csrfToken: csrfToken },
>     };
> }
> ```
> 
> Also, as I was verifying the lack of leaking secrets, someone over at React has a similar concern.
> 
> <img alt="image" width="836" src="https://user-images.githubusercontent.com/13663402/134409546-f5dc702c-3d0b-4823-be5b-fb2b4fe950b8.png">

After using this and current documentation I am getting another error from API

```
message: 'Signed cookie string must be provided.'
```

**Comment by amit-viacon** [comment]
This doesn't work
```ts
       const response = await fetch('/api/protected', {
            'headers': {
                'XSRF-TOKEN': csrfToken,
            }
        });
```

As it is trying to get the token from cookie:
https://github.com/j0lv3r4/next-csrf/blob/6f6de6b8269d1af785509680b73f53305f6ffe03/src/cookies/getCookie.ts#L6

Fixed by setting the cookie using ```document.cookie```

**Comment by sicarius97** [comment]
@j0lv3r4 I am trying to run a similar implementation to the one about using getServerSideProps but I get a 500 error when trying to make a post request to my login api route passing the csrfToken prop in the XSRF-TOKEN header. My handler works just fine without it, but when I wrap it in the csrf function being exported by my csrf.js module, it gives me a 500. Any ideas on this? Pretty much a standard nextjs project that is going to be deployed serverless

**Comment by j0lv3r4** [comment]
@sicarius97 I'm working on an example that does that and I ran into a similar issue. If you are in the Next.js Discord let's connect sometime soon and I will tell you about my findings.

**Comment by sicarius97** [comment]
@j0lv3r4 Sounds good, I currently am not in that discord but Id be happy to join, what is the link?

**Comment by j0lv3r4** [comment]
@sicarius97 https://discord.gg/v6jKNGXWXY

**Comment by afif-dev** [comment]
@Brawl345,  I got a similar error but I fix with this way

const options = {
  secret: `"${process.env.CSRF_SECRET}"`,
};

**Comment by afif-dev** [comment]
@Brawl345,  I got a similar error but I fix with this way

![image](https://user-images.githubusercontent.com/8979472/140958049-acbd11b9-a377-40da-8819-3b70d69ca9c4.png)

**Comment by Brawl345** [comment]
@afif-dev this will leak your secret in the bundle, don't do it

**Comment by afif-dev** [comment]
> @afif-dev this will leak your secret in the bundle, don't do it

mm.. I don't see any leak secret on my bundle. can you show me how it leaks?

![image](https://user-images.githubusercontent.com/8979472/140973135-160ff141-d34e-4f03-8d70-d0e519dbb2c4.png)

**Comment by danielfamiyeh** [comment]
@amit-viacon @j0lv3r4 @sicarius97 - Did any of you work out how to get past this internal server issue?

**Comment by j0lv3r4** [comment]
This got fixed in the last release. Thanks for the info all!
