### ISSUE TITLE
Broken middleware

### ISSUE THREAD

**Issue by yuriharrison** [j0lv3r4/next-csrf#30]
I'm having some problems getting the package to work and debugging it I found some issues on the middleware.

1. First one, middleware is breaking when trying to parse a cookie. There is no reason to parse anything here because `getToken` already returns the expected value for tokenFromHeaders.
https://github.com/j0lv3r4/next-csrf/blob/6f6de6b8269d1af785509680b73f53305f6ffe03/src/middleware/csrf.ts#L46

[PR to fix it](https://github.com/j0lv3r4/next-csrf/pull/31/files)

2. Another issue is the way you're using the csrf/Token package, the way it is setup right now every time a rebuild happens the `csrfSecret` changes and all open sessions start to fail on the tokens.verify check...

https://github.com/j0lv3r4/next-csrf/blob/6f6de6b8269d1af785509680b73f53305f6ffe03/src/middleware/csrf.ts#L69

and I need to reset the cookies (manually) to get it working again. That is annoying during development but not just that, the way it is right now you can't scale the application because each instance will be handling a different `csrfSecret`.

Possible solutions:
Use the same process.env.CSRF_TOKEN parameter when generating tokens on csrf/Token package;
Or accept a csrfSecret as a required parameter.

3. And lastly, I think passing the first request forward as if it was a valid request is an security issue. How would I protect the first request? I think it should be required a call to a different endpoint (not csrf protected) then it generates the first cookie and all csrf protected endpoints should be restricted on all calls.

**Comment by j0lv3r4** [comment]
@yuriharrison thanks for the PR!

I will review the other issue.

**Comment by j0lv3r4** [comment]
Fixed with https://github.com/j0lv3r4/next-csrf/releases/tag/v0.2.1 and @yuriharrison 's pr.
