### ISSUE TITLE
Parse method always returns an object

### ISSUE THREAD

**Issue by CarlinCanales** [j0lv3r4/next-csrf#32]
https://github.com/j0lv3r4/next-csrf/blob/6f6de6b8269d1af785509680b73f53305f6ffe03/src/middleware/csrf.ts#L46

In the above line, the parse method always returns an object, but you are immediately checking for `.length` which suggests you're expecting an array. So the `.length` always fails and I keep getting a `403` Invalid CSRF Token message. Is this a bug?

**Comment by j0lv3r4** [comment]
Fixed with https://github.com/j0lv3r4/next-csrf/pull/31
