### ISSUE TITLE
Do I use correctly next-csrf ??

### ISSUE THREAD

**Issue by nataliagoskapracuj** [j0lv3r4/next-csrf#33]
sorry for posting a question here, but I don't know if it's me who makes a mistake or is it problem with a package.
My application doesn't have a login or anything like this, so I created an empty endpoint that only sets a cookie when entering the page, and then I submit a form

My setup: 

```react.js
// service/csrf.js
import { nextCsrf } from "next-csrf";

const CSRF_SECRET = process.env.CSRF_SECRET;
const options = {
  secret: CSRF_SECRET
};

export const { csrf, csrfToken } = nextCsrf(options);
```

```react.js
//pages/api/csrf.js
import { csrf } from "service/csrf";

async function handler(req, res) {
  return res.status(200).end();
}

export default csrf(handler);
```

```react.js
//pages/_app.js
import { csrfToken } from "service/csrf";

function MyApp({ Component, pageProps }) {
  return (
      <Component {...pageProps} csrfToken={csrfToken} />
  );
}
export default MyApp;
```

```react.js
// pages/index.js
export default function HomePage({
  csrfToken,
}) {
  useEffect(() => {
  // first request to set a cookie
    apiRequest({
      method: httpMethods.GET,
      url: "api/csrf",
      headers: {
        "XSRF-TOKEN": csrfToken,
      },
    });
  }, []);

  return (
          <Form
            csrfToken={csrfToken}
          />
  );
}

```

```react.js

const Form = ({ csrfToken }) => {
  const handleSubmit = (event) => {
    event.preventDefault();
    apiRequest({
      method:  "POST",
      url: `api/send-form`,
      data: {
          //....
      },
      headers: {
        "XSRF-TOKEN": csrfToken,
      },
    })
      .then(() => {
      })
      .catch((error) => {
      });
  };

  return (
        <form onSubmit={handleSubmit}>
             //....
        </form>
  );
};

```

```react.js
// pages/api/send-form.js

import { csrf } from "service/csrf";

async function handler(req, res) {
 // ....
}

export default csrf(handler);
```

It returns 403 at this moment https://github.com/j0lv3r4/next-csrf/blob/main/src/middleware/csrf.ts#L64

I changed a package in node module to reflect the last changes that where made in this PR https://github.com/j0lv3r4/next-csrf/pull/31 because there is no new version of package with those changes.

**Comment by j0lv3r4** [comment]
Hey, @nataliagoskapracuj. I need to make a new release, but I haven't had the time.

I will try to get it done this weekend.

**Comment by nizarfadlan** [comment]
> Hey, @nataliagoskapracuj. I need to make a new release, but I haven't had the time.
> 
> I will try to get it done this weekend.


I'm waiting for it sir, hopefully it will be released soon

**Comment by akeuk** [comment]
@j0lv3r4 Can we workaround by using older released?

**Comment by j0lv3r4** [comment]
This got fixed with https://github.com/j0lv3r4/next-csrf/releases/tag/v0.2.1

**Comment by j0lv3r4** [comment]
I'm going to close this. Please re-open if you are still having this issue.
