### ISSUE TITLE
how to use in API endpoint

### ISSUE THREAD

**Issue by nizarfadlan** [j0lv3r4/next-csrf#36]
On the API page but my requests with `XSRF-TOKEN` header turned out to be error 500, can anyone help?
I tried console.log csrf normally comes out csrf but why can't request.

```
// pages/api/yt.js
const ytdl = require('ytdl-core');
import { csrf } from '@/lib/csrf';

async function handler(req, res) {
  if (req.method === 'POST') {
    try{
      const url  = req.body.url;
      const type = req.body.type;
      if(type === "mp3"){
        res.setHeader('content-type', "audio/mpeg");
        await ytdl(url, {
          format: 'mp3',
          filter: 'audioonly',
        }).pipe(res);
      }else if(type === "mp4"){
        res.setHeader('content-type', "video/mp4");
        await ytdl(url).pipe(res);
      }
    }catch(err){
      console.log('err: ', err);
    }
  } else {
    res.status(400).json({ result: false })
  }
}

export default csrf(handler);
```

if i don't use csrf then it's safe no error but when i use `..csrf(handler)` it will be problematic

```
// components/YT.js
...
const requestOptions = {
  method: 'POST',
  headers: { 'Content-Type': 'application/json', 'XSRF-TOKEN': csrfToken },
  body: JSON.stringify({ url, type:"mp4" })
};
console.log(requestOptions);
fetch(`${domain}/api/yt`, requestOptions)
.then( res => res.blob() )
.then( blob => {
  const sizeInBytes = blob.size;
  setShowProcess(false);
  if(sizeInBytes <=0){
    setInfo(["Unable to download! Maybe File size is too high. Try to download video less than 5MB", 2]);
  }else{
    download(blob,`${title}.mp4`,"video/mp4");
    setInfo(["Ready for download!", 3]);
  }
});
...
```

**Comment by vla-dev** [comment]
can you attach here the request headers and the response message?

**Comment by nizarfadlan** [comment]
> can you attach here the request headers and the response message?

This requests body and header
```
// Body Requests
{"url":"https://www.youtube.com/watch?v=JAzdEv-U2wY","type":"mp3"}

// Header Requests
POST /api/yt HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 66
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
XSRF-TOKEN: awaSOT1C-aTpmGqI4aYDAyEjAxwIAF7y8evk.QxxJzPThkDGu3oSJYXXNnhTH4M7D7Jib13N5eDP8yjU
DNT: 1
Content-Type: application/json
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
sec-ch-ua-platform: "Windows"
Accept: */*
Origin: http://localhost:3000
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,id-ID;q=0.8,id;q=0.7
Cookie: session=Fe26.2*1*a353b9d660d0bb3082cef0fc05cc8443796279a49da6284d1c24c1402a233b23*w7gCCobxBEqmIg_9b2MG6w*t_n0pwhhjf-f6jQSxph3YGNlaljKBYgIzWahbqgjySnBGCyxDRzBGkqj0GK9y2ssuNtN7Xa3G73uC2lA8X3e05buyyhrwC5cAxUbBQomuYY*1639733872066678*e71c06f5e3200c3a2c9b60230173bf70e53c19c7a80ede9eae2483829fb94741*hMsfU-Q10dzF7ArusPxKWg74eebxZZ-3ndWkURstTIs; dom3ic8zudi28v8lr6fgphwffqoz0j6c=8d120fc1-450d-465b-9508-012b728ad8a5%3A2%3A1; m5a4xojbcp2nx3gptmm633qal3gzmadn=grandchildfee.com
```

Not response message because response code `500 Internal Server Error`

**Comment by vla-dev** [comment]
Since you have other cookies (`Cookie: session=Fe24.2*......`) on the request headers, it might be the same issue as the previous one: (https://github.com/j0lv3r4/next-csrf/issues/35) where I already open a pull request with the fix.

As an easy fix, you can make your own middleware to populate the existing cookie from request headers:

`lib/csrf.js`
```
const options = {
    tokenKey: "XSRF-TOKEN",
    secret: 'secretkey'
}

const {csrf, csrfToken} = nextCsrf(options)

const patchedCsrf = (handler) => async (req, res) => {
    if (req.headers.cookie != null) {
        const parsedCookie = parse(req.headers.cookie);
        if (!parsedCookie[options.tokenKey]) {
            req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
        }
    }

    return csrf(handler)(req, res);
}

export {
    patchedCsrf as csrf,
    csrfToken
}
```

Hopefully, this will help you.

**Comment by nizarfadlan** [comment]
> Since you have other cookies (`Cookie: session=Fe24.2*......`) on the request headers, it might be the same issue as the previous one: (#35) where I already open a pull request with the fix.
> 
> As an easy fix, you can make your own middleware to populate the existing cookie from request headers:
> 
> `lib/csrf.js`
> 
> ```
> const options = {
>     tokenKey: "XSRF-TOKEN",
>     secret: 'secretkey'
> }
> 
> const {csrf, csrfToken} = nextCsrf(options)
> 
> const patchedCsrf = (handler) => async (req, res) => {
>     if (req.headers.cookie != null) {
>         const parsedCookie = parse(req.headers.cookie);
>         if (!parsedCookie[options.tokenKey]) {
>             req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
>         }
>     }
> 
>     return csrf(handler)(req, res);
> }
> 
> export {
>     patchedCsrf as csrf,
>     csrfToken
> }
> ```
> 
> Hopefully, this will help you.

Only change middleware?

in nextJS how to use 
```
const parsedCookie = parse(req.headers.cookie);
...
req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
```

use JSON?

**Comment by nizarfadlan** [comment]
> Since you have other cookies (`Cookie: session=Fe24.2*......`) on the request headers, it might be the same issue as the previous one: (#35) where I already open a pull request with the fix.
> 
> As an easy fix, you can make your own middleware to populate the existing cookie from request headers:
> 
> `lib/csrf.js`
> 
> ```
> const options = {
>     tokenKey: "XSRF-TOKEN",
>     secret: 'secretkey'
> }
> 
> const {csrf, csrfToken} = nextCsrf(options)
> 
> const patchedCsrf = (handler) => async (req, res) => {
>     if (req.headers.cookie != null) {
>         const parsedCookie = parse(req.headers.cookie);
>         if (!parsedCookie[options.tokenKey]) {
>             req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
>         }
>     }
> 
>     return csrf(handler)(req, res);
> }
> 
> export {
>     patchedCsrf as csrf,
>     csrfToken
> }
> ```
> 
> Hopefully, this will help you.

Thanks sir

**Comment by nizarfadlan** [comment]
> Since you have other cookies (`Cookie: session=Fe24.2*......`) on the request headers, it might be the same issue as the previous one: (#35) where I already open a pull request with the fix.
> 
> As an easy fix, you can make your own middleware to populate the existing cookie from request headers:
> 
> `lib/csrf.js`
> 
> ```
> const options = {
>     tokenKey: "XSRF-TOKEN",
>     secret: 'secretkey'
> }
> 
> const {csrf, csrfToken} = nextCsrf(options)
> 
> const patchedCsrf = (handler) => async (req, res) => {
>     if (req.headers.cookie != null) {
>         const parsedCookie = parse(req.headers.cookie);
>         if (!parsedCookie[options.tokenKey]) {
>             req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
>         }
>     }
> 
>     return csrf(handler)(req, res);
> }
> 
> export {
>     patchedCsrf as csrf,
>     csrfToken
> }
> ```
> 
> Hopefully, this will help you.

after the requests cookie in the header is not refreshed with the new csrf token this results in a 403 error

**Comment by shane-arthur** [comment]
Same this will only work once per session as the withCsrf util only runs on init..

**Comment by IrhadOmanovic** [comment]
What you can do is to make cookie expire in couple of seconds like this:

`import { nextCsrf } from 'next-csrf'
import { parse, serialize } from 'cookie'

const options = {
  tokenKey      : 'XSRF-TOKEN',
  secret        : process.env.CSRF_SECRET,
  cookieOptions : {
    httpOnly : true,
    path     : '/',
    secure   : process.env.NODE_ENV === 'production',
    maxAge   : 4
  }
}

const { csrf, csrfToken } = nextCsrf(options)

const patchedCsrf = (handler) => async (req, res) => {
  if (req.headers.cookie != null) {
    const parsedCookie = parse(req.headers.cookie)
    if (!parsedCookie[options.tokenKey]) {
      req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
    }
  }

  return csrf(handler)(req, res)
}

export {
  patchedCsrf as csrf,
  csrfToken
}
`

This way, user will be able to make as many requests as he wishes. This stuff worked for me.

**Comment by ateufel** [comment]
with the latest solution, i can do GET requests, but i get a 403 error on POST requests. does anyone else have that problem?

**Comment by ateufel** [comment]
```
const patchedCsrf = (handler) => async (req, res) => {
    console.log(csrfToken);
    if (req.headers.cookie != null) {
        const parsedCookie = parse(req.headers.cookie)
        if (parsedCookie[options.tokenKey]) {
            req.headers.cookie = `${serialize(options.tokenKey, parsedCookie[options.tokenKey])}`
        }
        console.log(req.headers.cookie);
    }
    return csrf(handler)(req, res)
};
```
The token on the server is different from the cookie token, maybe that helps to solve issue?

Output:
```
UtoE6IjR-DGElUUG2AvLVQOHhbG_qSairXJ4.8OUMuy665jBAeiRHR8QSk3WdqAIZRP+ZNaSJ1TnqX/M
XSRF-TOKEN=LBuSuyFm-LEoHrUiaZIaazBm0FgCLgp0Uim8.2gnoZsxsYFFhblQeooF5WVVa6vwT3yEZt2GkpbHUtfY
```

**Comment by nizarfadlan** [comment]
> ```
> const patchedCsrf = (handler) => async (req, res) => {
>     console.log(csrfToken);
>     if (req.headers.cookie != null) {
>         const parsedCookie = parse(req.headers.cookie)
>         if (parsedCookie[options.tokenKey]) {
>             req.headers.cookie = `${serialize(options.tokenKey, parsedCookie[options.tokenKey])}`
>         }
>         console.log(req.headers.cookie);
>     }
>     return csrf(handler)(req, res)
> };
> ```
> 
> The token on the server is different from the cookie token, maybe that helps to solve issue?
> 
> Output:
> 
> ```
> UtoE6IjR-DGElUUG2AvLVQOHhbG_qSairXJ4.8OUMuy665jBAeiRHR8QSk3WdqAIZRP+ZNaSJ1TnqX/M
> XSRF-TOKEN=LBuSuyFm-LEoHrUiaZIaazBm0FgCLgp0Uim8.2gnoZsxsYFFhblQeooF5WVVa6vwT3yEZt2GkpbHUtfY
> ```

thanks

**Comment by nizarfadlan** [comment]
@ateufel I left this a long time ago because there was no solution and I switched to next-auth

**Comment by cdking007** [comment]
if i did not provide csrf token to my api request i want to stop the api to get call or send response. is there any work around how do i implement this or any way to validate csrf token that send through the header in api request?

**Comment by Darren120** [comment]
> import { nextCsrf } from 'next-csrf'
> import { parse, serialize } from 'cookie'
> 
> const options = {
>   tokenKey      : 'XSRF-TOKEN',
>   secret        : process.env.CSRF_SECRET,
>   cookieOptions : {
>     httpOnly : true,
>     path     : '/',
>     secure   : process.env.NODE_ENV === 'production',
>     maxAge   : 4
>   }
> }
> 
> const { csrf, csrfToken } = nextCsrf(options)
> 
> const patchedCsrf = (handler) => async (req, res) => {
>   if (req.headers.cookie != null) {
>     const parsedCookie = parse(req.headers.cookie)
>     if (!parsedCookie[options.tokenKey]) {
>       req.headers.cookie += `; ${serialize(options.tokenKey, '')}`
>     }
>   }
> 
>   return csrf(handler)(req, res)
> }
> 
> export {
>   patchedCsrf as csrf,
>   csrfToken
> }

no csrf here

**Comment by j0lv3r4** [comment]
This got fixed with https://github.com/j0lv3r4/next-csrf/releases/tag/v0.2.1. Please take a look at the updated example.
