### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Darren120** [j0lv3r4/next-csrf#38]
I legit copied the docs. I get internal server error. if i remove the csrf(func) wrapper the error goes away

**Comment by j0lv3r4** [comment]
This got fixed with https://github.com/j0lv3r4/next-csrf/releases/tag/v0.2.1. Take a look at the updated example.

**Comment by j0lv3r4** [comment]
@Darren120 going to close this, feel free to re-open it if the issue persists.
