### ISSUE TITLE
Typo in file name

### ISSUE THREAD

**Issue by EdwinGuzman** [j0lv3r4/next-csrf#4]
Thanks for writing this.

When trying to use this, I'm finding that the documentation may be lacking some information. But following it I found this issue:

`TypeError: Cannot read property 'inherits' of undefined`
`.../node_modules/next-csrf/dist/next-csrf.js:107:21)`

I installed the repo locally and found that `/src/csrf/indext.ts` should be `/src/csrf/index.ts` without the `t` after the `x`.

**Comment by j0lv3r4** [comment]
:facepalm: my bad.

Thanks for the heads up! I'm committing a fix soon.
